<div class="product-img-wrp" data-mage-init='{"productSlider":{}}'>
    <div class="img-box">
        <img src="<?php echo $this->getViewFileUrl('images/p5.png'); ?>" alt="product-img">
    </div>
    <div class="img-box">
        <img src="<?php echo $this->getViewFileUrl('images/p1.png'); ?>" alt="product-img">
    </div>
    <div class="img-box">
        <img src="<?php echo $this->getViewFileUrl('images/p2.png'); ?>" alt="product-img">
    </div>
    <div class="img-box">
        <img src="<?php echo $this->getViewFileUrl('images/p3.png'); ?>" alt="product-img">
    </div>
    <div class="img-box">
        <img src="<?php echo $this->getViewFileUrl('images/p4.png'); ?>" alt="product-img">
    </div>
</div>
