<!--  BANNER SLIDER  -->
<div class="category-banner" >
    <div class="category-banner-wrp" data-mage-init='{"slickSlider":{}}'>
    <!--  1. slide  -->
            <div class="slide">
                <a href="#">
                    <div class="slide__image">
                        <img src="<?php echo $this->getViewFileUrl('images/myfolder/banner1.jpg'); ?>" alt="banner">
                    </div>
                </a>
            </div>
    <!--  2. slide  -->
            <div class="slide">
                <a href="#">

                    <div class="slide__image">
                        <img src="<?php echo $this->getViewFileUrl('images/myfolder/banner2.jpg'); ?>" alt="banner">
                    </div>
                </a>
            </div>
    <!--  3. slide  -->
            <div class="slide">
                <a href="#">
                    <div class="slide__image">
                        <img src="<?php echo $this->getViewFileUrl('images/myfolder/banner3.jpg'); ?>" alt="banner">
                    </div>
                </a>
            </div>

    </div>
</div>